### ISSUE TITLE
Remove Github Actions redundancy

### ISSUE THREAD

**Issue by ddriddle** [techservicesillinois/awscli-login#148]
Currently, the tests are fired on push and pull_request. We need to restrict testing to push only on merge to master. Something like this:

```yaml
on:
  push:
    branches:
      - main
  pull_request:
```

## Tasks

- [ ] replace the `on` block in `cicd.yml` with the above.
