### ISSUE TITLE
Fix release on tag

### ISSUE THREAD

**Issue by ddriddle** [techservicesillinois/awscli-login#244]
I tagged the default branch with version 1.0 but a new release was not pushed to PyPI, because Github Action's did not trigger at all. This needs fixing, otherwise we can not make production releases!

**Comment by ddriddle** [comment]
Relevant documentation:

> ### Example: Including branches and tags
>
> The patterns defined in branches and tags are evaluated against the Git ref's name. For example, the following workflow would run whenever there is a push event to:
>
> * A branch named main (refs/heads/main)
> * A branch named mona/octocat (refs/heads/mona/octocat)
> * A branch whose name starts with releases/, like releases/10 (refs/heads/releases/10)
> * A tag named v2 (refs/tags/v2)
> * A tag whose name starts with v1., like v1.9.1 (refs/tags/v1.9.1)
> 
```yaml
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - main
      - 'mona/octocat'
      - 'releases/**'
    # Sequence of patterns matched against refs/tags
    tags:
      - v2
      - v1.*
```
> https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#example-including-branches-and-tags
